# Generated by Django 3.2.8 on 2021-10-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_id', models.IntegerField(blank=True, null=True)),
                ('genotype', models.CharField(blank=True, max_length=255, null=True)),
                ('bloodline', models.CharField(blank=True, max_length=255, null=True)),
                ('breed_type', models.CharField(blank=True, max_length=255, null=True)),
                ('horse_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horses',
            },
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
