# Generated by Django 3.2.8 on 2021-10-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20211009_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horses',
            name='id',
        ),
        migrations.AlterField(
            model_name='horses',
            name='horse_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
