# Generated by Django 3.2.8 on 2021-10-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20211009_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horses',
            old_name='horse_id',
            new_name='id',
        ),
    ]
